### ISSUE TITLE
Upgrade Apache Commons Collections to v3.2.2

### ISSUE THREAD

**Issue by jart** [zorzella/guiceberry#31]
I noticed you have `doc/tutorial/lib/commons-collections-3.2.1.jar` in your source tree.

Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!

https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

**Comment by zorzella** [comment]
Thank you for your report. Sorry for the delay. Here's the commit:
