### ISSUE TITLE
Release latest GuiceBerry on Maven

### ISSUE THREAD

**Issue by timothybasanov** [zorzella/guiceberry#37]
It would be super nice if latest GuiceBerry would be available on Maven central repo.
Latest version available is 3.3.1, which is pretty old.
Many developers only use maven to download new versions of well-known libraries. 
I was not aware that 4.x branch even exists until I tried to submit a patch myself.

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by codemak2r** [comment]
it seems that no one maintains this repository now.

**Comment by zorzella** [comment]
Closing old/obsolete issues.
