### ISSUE TITLE
Defining a GuiceBerryRule by passing a Supplier<Module>

### ISSUE THREAD

**Issue by Bocete** [zorzella/guiceberry#38]
The idea is simple. Right now, to be in control over which modules are used for injection in each test class, I have to create an inner class that's a Module that installs all the Modules I want to use. Then my GuiceBerryRule can refer to this class.

Example:

```
public final class MyTestClass {
  @Rule
  public final GuiceBerryRule guiceBerry = new GuiceBerryRule(MyTestClassModule.class);

  public static final class MyTestClassModule extends AbstractModule {
    @Override
    protected void configure() {
      install(...);
      install(...);
      ...
    }
  }
}
```

Instead, we could be able to just say:

```
public final class MyTestClass {
  @Rule
  public final GuiceBerryRule guiceBerry = new GuiceBerryRule(() -> Modules.combine(...));
}
```

Besides getting rid of a lot of bloat in what I see to be a very common pattern in my company, this would give the user more direct power over which modules are used by GuiceBerry. E.g. you could make GuiceBerry use the same module object for multiple tests, if you wish.

It's a very simple feature, but spanning quite a few changes on GuiceBerry's side. I realize it's not a quick fix. I'm curious if this is a good idea more than anything else. If you think it's a cool idea I'd like to try implementing it if I can find the time.

**Comment by zorzella** [comment]
Closing old/obsolete issues.
