### ISSUE TITLE
Broken hyperlinks in README

### ISSUE THREAD

**Issue by umang94** [zorzella/guiceberry#39]
These links to the doc and slides in README.md are invalid.

* Doc: http://docs.google.com/View?id=dddf9mmq_29s3s79fcv
* Slides: https://docs.google.com/present/view?id=dddf9mmq_30fgnf9jc2

**Comment by zorzella** [comment]
Thanks for reporting. This is fixed... Google apparently changed the format of the URLs for these docs.
