### ISSUE TITLE
Maven-ize GuiceBerry

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zorzella/guiceberry#6]
```
Is there any chance GuiceBerry to be mavenized ? 

It would be really nice if GuiceBerry can be used as a maven artifact.

```

Original issue reported on code.google.com by `MGe...@gmail.com` on 29 Mar 2009 at 12:20

**Comment by zorzella** [comment]
With the upgrade to GuiceBerry 4.0.0 we broke the link to TL4J (in favor of guava-testlibs), and it should be simpler to Mavenize it now. Will someone help me with a patch?

**Comment by The-Alchemist** [comment]
@zorzella : Hi there!  I can help with a Maven patch (I already have some stuff on Maven Central, so I'm kinda familiar with the process).  Has any work been started, so we don't have to start from scratch?

**Comment by zorzella** [comment]
Closing old/obsolete issues.
